services:
  mysql:
    image: 'mysql:8.4'
    container_name: gametracker-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_pgt
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
